CREATE TABLE `U_USER` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` VARCHAR(30) NOT NULL COMMENT 'USER_ID',
  `ACCOUNT` VARCHAR(30) NOT NULL COMMENT 'ACCOUNT',
  `USERNAME` VARCHAR(30) NOT NULL COMMENT '用户姓名',
  `PASSWORD` VARCHAR(50) NOT NULL COMMENT '登录密码',
  `STATUS` VARCHAR(2) NOT NULL COMMENT '状态，01：正常，02：锁定',
  `SALT` VARCHAR(100) DEFAULT NULL COMMENT '用于加密的盐',
  `MOBILE` VARCHAR(20) DEFAULT NULL COMMENT '手机号',
  `EMAIL` VARCHAR(50) DEFAULT NULL COMMENT '申请人姓名',
  `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
  `CREATE_USER_ID` VARCHAR(30) NOT NULL COMMENT '创建人USER_ID',
  `LAST_UPDATE_USER_ID` VARCHAR(30) NOT NULL COMMENT '最后一次更新人USER_ID',
  `LAST_UPDATE_TIME` TIMESTAMP COMMENT '最后一次更新时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USER_ID`(`USER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='用户表';


