CREATE TABLE `U_USER_LOGIN_RECORD` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` VARCHAR(30) NOT NULL COMMENT 'USER_ID',
  `USERNAME` VARCHAR(30) NOT NULL COMMENT '用户姓名',
  `IP` VARCHAR(30) NOT NULL COMMENT 'IP',
  `USER_AGENT` VARCHAR(200) DEFAULT NULL,
  `ACCEPT_LANGUAGE` VARCHAR(200) DEFAULT NULL,
  `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
  `CREATE_USER_ID` VARCHAR(30) NOT NULL COMMENT '创建人USER_ID',
  `LAST_UPDATE_USER_ID` VARCHAR(30) NOT NULL COMMENT '最后一次更新人USER_ID',
  `LAST_UPDATE_TIME` TIMESTAMP COMMENT '最后一次更新时间',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='用户登录信息记录表';