CREATE TABLE `U_USER_DETAIL` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` VARCHAR(30) NOT NULL COMMENT 'USER_ID',
  `DESC` VARCHAR(200) NOT NULL COMMENT '描述',
  `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
  `CREATE_USER_ID` VARCHAR(30) NOT NULL COMMENT '创建人USER_ID',
  `LAST_UPDATE_USER_ID` VARCHAR(30) NOT NULL COMMENT '最后一次更新人USER_ID',
  `LAST_UPDATE_TIME` TIMESTAMP COMMENT '最后一次更新时间',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USER_ID`(`USER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='用户详细表';
