CREATE TABLE `LOG_CONTROLLER_METHOD_RECORD` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` VARCHAR(30) DEFAULT NULL COMMENT 'USER_ID',
  `METHOD_NAME` VARCHAR(100) NOT NULL COMMENT '方法名',
  `PARAMETER_COUNT` INT(3) NOT NULL COMMENT '参数个数',
  `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
  `CREATE_USER_ID` VARCHAR(30) DEFAULT NULL COMMENT '创建人USER_ID',
  `LAST_UPDATE_USER_ID` VARCHAR(30) DEFAULT NULL COMMENT '最后一次更新人USER_ID',
  `LAST_UPDATE_TIME` TIMESTAMP COMMENT '最后一次更新时间',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='用户访问Controller记录表';