CREATE TABLE TEST_PERSON (
`ID` INT(30) NOT NULL AUTO_INCREMENT COMMENT 'ID',
`USERNAME` VARCHAR(50) NOT NULL COMMENT '用户名',
`PASSWORD` VARCHAR(100) NOT NULL COMMENT '密码',
`NAME` VARCHAR(50) NOT NULL COMMENT '姓名',
`SEX` INT(1) DEFAULT NULL COMMENT '性别',
`PHONE` VARCHAR(30) DEFAULT NULL COMMENT '手机号',
`EMAIL` VARCHAR(120) DEFAULT NULL COMMENT '邮箱',
`REMARKS` VARCHAR(1020) DEFAULT NULL COMMENT '备注',
PRIMARY KEY (`ID`),
UNIQUE KEY (`USERNAME`),
UNIQUE KEY (`PHONE`),
UNIQUE KEY (`EMAIL`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='TEST-人员表';